# Generated by Django 2.1.3 on 2018-12-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
