# Generated by Django 2.1.3 on 2018-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20181204_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
